name: Rust

on:
  push:
    branches: [ main ,staging,trying]
    paths-ignore:
      - '*.md'
  # pull_request:
    # branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{matrix.os}}
    name: Run test
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.0

    - name: Run cargo tests
      run: cargo test --verbose
