name: Rust

on:
  push:
    branches: [ main ,staging,trying]
    paths-ignore:
      - '*.md'
  pull_request:
  #   branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    - run: echo "hello"
