name: Rust

on:
  push:
    branches: [staging,trying]
    paths-ignore:
      - '*.md'
  pull_request:
  #   branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    - run: echo "hello"
  ci-success:
    name: ci
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
